import '../globals.css'
import { Inter, Pattaya, Roboto_Mono, Rampart_One, Berkshire_Swash } from 'next/font/google';
import Navbar from '../components/Navbar';

const pattaya = Pattaya({ 
  subsets: ['latin'],
  weight:["400"],
  variable: '--font-pattaya',
});
 const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
 
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})
const rampart = Rampart_One({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rampart',
  weight: '400'
})
const swash = Berkshire_Swash({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rampart',
  weight: '400'
})

export const metadata = {
  title: 'Jessika Gyllström Portfolio',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>    
        <Navbar/>
        <main className={`${inter.variable} ${pattaya.variable}`}>{children}</main>
      </body>
    </html>
  )
}
