import { createClient } from 'next-sanity';
import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer';
import Art from '../pages/art'
import UploadcareImage from '@uploadcare/nextjs-loader';
import Image from 'next/image'
import Hero from '../components/Hero'
import { sanityClient, urlFor } from '../lib/sanity';
import imageUrlBuilder from '@sanity/image-url'

const builder = imageUrlBuilder(sanityClient)

function Home( {posts} ) {
  return (
    <div>
      <Head>
        <title>Jessika Gyllström Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>    
      <Header />
      <Hero />
      <Skills posts={posts} />
      <div></div>
      <Footer />
    </div>
  )
}
export async function getStaticProps() {
  const posts = await sanityClient.fetch(`*[_type == "skills"]`)
  return { props: { posts }}
}
function Skills({ posts }) {
  return (
    <div className='flex justify-center'>
    {posts.map((post, id) => 
    <div key={id} className='flex flex-col p-5'>
      <h3 className='font-normal' > { post.title }</h3>
      {post.description.map((post, id) => 
        <p>{post}</p>
      )}
    </div>
    )} 
  </div>
  )
}
export default Home;