import { createClient } from 'next-sanity';
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import { sanityClient } from '../lib/sanity';
import styles from '../styles/Home.module.css'
const postQuery = `*[_type == "post"]`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jessika Gyllström Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
        
        <main>
   
      </main>

      <footer className='flex justify-center sticky bottom-0'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        Created by: Jessika Gyllström
        </a>
      </footer>
    </div>
  )
}
export async function getStaticProps() {
  const posts = await sanityClient.fetch(`*[_type == "post"]`)
  console.log(posts)
  return { props: { posts }}
}