import { createClient } from 'next-sanity';
import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer';
import Contact from './js-form';
import Art from '../pages/art'
import UploadcareImage from '@uploadcare/nextjs-loader';
import Image from 'next/image'
import Hero from '../components/Hero'
import { sanityClient, urlFor } from '../lib/sanity';
import imageUrlBuilder from '@sanity/image-url'

const builder = imageUrlBuilder(sanityClient)

function Home( {posts} ) {
  return (
    <div>
      <Head>
        <title>Jessika Gyllström Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>    
      <Header />
      <Hero />
      <Skills posts={posts} />
      <Contact />
      <Footer />
    </div>
  )
}
export async function getStaticProps() {
  const posts = await sanityClient.fetch(`*[_type == "skills"]`)
  return { props: { posts }}
}
function Skills({ posts }) {
  return (
      <div className='py-10'>
        <fieldset className="border-t border-gray-700 mb-10">
          <legend className="mx-auto px-4 text-white text-2xl italic">Skills</legend>
        </fieldset>
        <div className='flex justify-center content-center mx-auto h-[80%]'>
          <div className='flex justify-center flex-col md:flex-row md:w-[80%]'>
            {posts.map((post, id) => 
              <div key={id} className='flex flex-col mx-auto m-3 w-[60%] sm:w-[40%] md:w-[60] lg:w-[30%] rounded-xl bg-neutral-800  shadow-purple-800 shadow-[0_0_10px_0] hover:scale-[1.02] transition ease-in-out delay-850'>
                <img className="rounded-t-xl" src={urlFor(`${post.image.asset._ref}`).url()}/>
                <div className='py-3 px-4'>
                  <h3 className='text-xs font-bold' > { post.title }</h3>
                    {post.description.map((post, id) => 
                      <p key={id} className='text-xs'>{post}</p>
                    )}
                </div>    
              </div>
            )} 
          </div>
        </div>
    </div>
  )
}
export default Home;